export const mockCocktails = [
  {
    idDrink: "12944",
    strDrink: "Gluehwein",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Punch / Party Drink",
    strIBA: null,
    strAlcoholic: "Optional alcohol",
    strGlass: "Irish coffee cup",
    strInstructions:
      "Boil sugar and spices in water, leave in the water for 30 minutes. Strain the spiced water and mix with the wine. Heat slowly until short of boiling temperature. (To remove alcohol, let it boil for a while.) You may add lemon or orange juice to taste. Serve in irish coffee cup.",
    strInstructionsES: null,
    strInstructionsDE:
      "Zucker und Gewürze in Wasser kochen, 30 Minuten im Wasser ziehen lassen. Das gewürzte Wasser abgießen und mit dem Wein mischen. Langsam erhitzen, bis die Siedetemperatur erreicht ist. (Um Alkohol zu entfernen, lassen Sie ihn eine Weile kochen.) Sie können Zitronen- oder Orangensaft nach Belieben hinzufügen. In einer irischen Kaffeetasse servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Far bollire lo zucchero e le spezie in acqua, lasciare in acqua per 30 minuti.\r\nFiltrate l'acqua speziata e mescolatela con il vino.\r\nRiscaldare lentamente fino a raggiungere la temperatura di ebollizione.\r\n(Per rimuovere l'alcol, lascialo bollire per un po '.) Puoi aggiungere succo di limone o arancia a piacere.\r\nServire in tazza di caffè irlandese.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vuxwvt1468875418.jpg",
    strIngredient1: "Red wine",
    strIngredient2: "Water",
    strIngredient3: "Sugar",
    strIngredient4: "Cinnamon",
    strIngredient5: "Cloves",
    strIngredient6: "Lemon peel",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 L ",
    strMeasure2: "125 ml ",
    strMeasure3: "60 gr ",
    strMeasure4: "1 ",
    strMeasure5: "3 ",
    strMeasure6: "1 tblsp ",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-07-18 21:56:58",
  },
  {
    idDrink: "16108",
    strDrink: "9 1/2 Weeks",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Combine all ingredients in glass mixer. Chill and strain into Cocktail glass. Garnish with sliced strawberry.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einem Glasmischer vermengen. Abkühlen lassen und in das Cocktailglas abseihen. Mit Erdbeerscheiben garnieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Unisci tutti gli ingredienti in una planetaria.\r\nRaffredda e versa in un bicchiere da cocktail.\r\nGuarnire con la fragola a fette.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/xvwusr1472669302.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Orange Curacao",
    strIngredient3: "Strawberry liqueur",
    strIngredient4: "Orange juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1 splash ",
    strMeasure4: "1 oz ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:48:22",
  },
  {
    idDrink: "16990",
    strDrink: "Sweet Tooth",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Shake",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball Glass",
    strInstructions:
      "Put 2 shots Godiva Liquour into a glass, add as much or as little milk as you would like.",
    strInstructionsES: null,
    strInstructionsDE:
      "Geben Sie 2 Spritzer Godiva Liquour in ein Glas, geben Sie so viel Milch hinzu, wie Sie möchten.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Metti 2 shot di Godiva Liqueur in un bicchiere, aggiungi tanto o poco latte quanto desideri.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/j6rq6h1503563821.jpg",
    strIngredient1: "Godiva liqueur",
    strIngredient2: "Milk",
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 shots ",
    strMeasure2: null,
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-08-24 09:37:01",
  },
  {
    idDrink: "12696",
    strDrink: "Lassi - Sweet",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Other / Unknown",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball glass",
    strInstructions:
      "Put all ingredients into a blender and blend until nice and frothy. Serve chilled.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in einen Mixer geben und schaumig rühren. Kühl servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Metti tutti gli ingredienti in un frullatore e frulla fino a ottenere un composto omogeneo e spumoso. Servire freddo.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/9jeifz1487603885.jpg",
    strIngredient1: "Yoghurt",
    strIngredient2: "Water",
    strIngredient3: "Sugar",
    strIngredient4: "Salt",
    strIngredient5: "Lemon juice",
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 cup ",
    strMeasure2: "2 cups cold ",
    strMeasure3: "4 tblsp ",
    strMeasure4: "pinch ",
    strMeasure5: "2 tblsp ",
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-02-20 15:18:05",
  },
  {
    idDrink: "12724",
    strDrink: "Sweet Bananas",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Shake",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Highball Glass",
    strInstructions:
      "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/sxpcj71487603345.jpg",
    strIngredient1: "Milk",
    strIngredient2: "Banana",
    strIngredient3: "Honey",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 cups ",
    strMeasure2: "1 ",
    strMeasure3: "1 tblsp ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-02-20 15:09:05",
  },
  {
    idDrink: "13024",
    strDrink: "Sweet Sangria",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Punch / Party Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Pitcher",
    strInstructions:
      "Dissolve the sugar in hot water and cool. Peel the citrus fruits and break into wedges. Mix the wine, sugar syrup, fruit, and Fresca in a pitcher and put in the fridge for a few hours. Serve in tall glasses with a straw.",
    strInstructionsES: null,
    strInstructionsDE:
      "Den Zucker in heißem Wasser auflösen und abkühlen lassen. Die Zitrusfrüchte schälen und stückeln. Wein, Zuckersirup, Obst und Fresca in einem Krug mischen und für einige Stunden in den Kühlschrank stellen. In hohen Gläsern mit einem Strohhalm servieren.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Sciogliere lo zucchero in acqua calda e raffreddare.\r\nPelare gli agrumi e spezzarli a spicchi.\r\nMescolare il vino, lo sciroppo di zucchero, la frutta e la Fresca in una caraffa e mettere in frigo per qualche ora.\r\nServire in bicchieri alti con una cannuccia.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/uqqvsp1468924228.jpg",
    strIngredient1: "Red wine",
    strIngredient2: "Sugar",
    strIngredient3: "Water",
    strIngredient4: "Apple",
    strIngredient5: "Orange",
    strIngredient6: "Lime",
    strIngredient7: "Lemon",
    strIngredient8: "Fresca",
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 bottles ",
    strMeasure2: "1 cup ",
    strMeasure3: "2 cups hot ",
    strMeasure4: "1 cup",
    strMeasure5: " wedges\n",
    strMeasure6: " wedges\n",
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-07-19 11:30:28",
  },
  {
    idDrink: "15521",
    strDrink: "Swedish Coffee",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Coffee / Tea",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Coffee Mug",
    strInstructions:
      "Pour the coffee in an ordinary coffee cup. Add the aquavit. Add sugar by taste. Stir and have a nice evening (morning)",
    strInstructionsES: null,
    strInstructionsDE:
      "Gießen Sie den Kaffee in eine normale Kaffeetasse. Füge den Aquavit hinzu. Nach Belieben Zucker zugeben. Rühren Sie um und genießen Sie einen schönen Abend.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare il caffè in una normale tazza da cappuccino.\r\nAggiungi l'acquavite.\r\nAggiungere lo zucchero a piacere.\r\nMescola e passa una bella serata/mattina",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/ywtrvt1441246783.jpg",
    strIngredient1: "Coffee",
    strIngredient2: "Aquavit",
    strIngredient3: "Sugar",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 cup",
    strMeasure2: "4 cl ",
    strMeasure3: "By taste ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2015-09-03 03:19:43",
  },
  {
    idDrink: "12954",
    strDrink: "Holloween Punch",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Punch / Party Drink",
    strIBA: null,
    strAlcoholic: "Non alcoholic",
    strGlass: "Punch bowl",
    strInstructions:
      'Take a bunch of grape juice and a bunch of fizzy stuff (club soda, ginger ale, lemonlime, whatever). Mix them in a punch bowl. Take orange sherbet and lime sherbet. Scoop out scoops and float them in the punch, let them melt a little so that a nasty film spreads all over the top of the punch but there are still "bubbles" in it in the form of sherbet scoops. Looks horrible, tastes just fine.',
    strInstructionsES: null,
    strInstructionsDE:
      'Nimm viel Traubensaft und kohlensäurehaltige Flüssigkeiten (Club-Soda, Ginger Ale, Zitronenlimonade, was auch immer). In einer Bowle mischen. Nehmen Sie Orangenbrause und Limettenbrause. Bläschen im Punsch schweben lassen, sie ein wenig zergehen lassen, so dass sich ein böser Film über die Oberseite des Punschs verteilt, aber es gibt immer noch "Blasen" in Form von Brause-Schälchen darin. Sieht schrecklich aus, schmeckt gut.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Prendi un mazzetto di succo d'uva e un po 'di roba frizzante (club soda, ginger ale, sprite, qualunque cosa).\r\nMescolali in una ciotola da punch.\r\nPrendi il sorbetto all'arancia e il sorbetto al lime.\r\nEstrarre le palette e farle galleggiare nel punch, lasciarle sciogliere un po 'in modo che una pellicola sgradevole si diffonda su tutta la parte superiore del punch ma ci siano ancora delle \"bolle\" sotto forma di palline di sorbetto.\r\nSembra orribile, ha un buon sapore.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/lfeoe41504888925.jpg",
    strIngredient1: "Grape juice",
    strIngredient2: "Carbonated soft drink",
    strIngredient3: "Sherbet",
    strIngredient4: "Sherbet",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: null,
    strMeasure2: ", orange\n",
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-08 17:42:05",
  },
  {
    idDrink: "178313",
    strDrink: "Halloween Punch",
    strDrinkAlternate: null,
    strTags: "Halloween",
    strVideo: null,
    strCategory: "Punch / Party Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Punch bowl",
    strInstructions:
      "Tip the cherry juice, orange peel, chilli, cinnamon sticks, cloves and ginger into a large saucepan. Simmer for 5 mins, then turn off the heat. Leave to cool, then chill for at least 4 hrs, or up to 2 days – the longer you leave it the more intense the flavours. If serving to young children, take the chilli out after a few hours.\r\n\r\nWhen you’re ready to serve, pour the juice into a jug. Serve in glass bottles or glasses and pop a straw in each. If you're adding vodka, do so at this stage. Dangle a fangs sweet from each glass.",
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare il succo di ciliegia, la buccia d'arancia, il peperoncino, i bastoncini di cannella, i chiodi di garofano e lo zenzero in una grande casseruola. Cuocere a fuoco lento per 5 minuti, quindi spegnere il fuoco. Raffreddare per almeno 4 ore o fino a 2 giorni: più a lungo lo lasci, più intensi sono i sapori. Se servi ai bambini piccoli, togli il peperoncino dopo alcune ore.\r\n\r\nQuando sei pronto per servire, versa il succo in una caraffa. Servire in bottiglie o bicchieri di vetro e inserire una cannuccia in ciascuno. Se stai aggiungendo la vodka, fallo in questa fase. Fai ciondolare una zanna dolce da ogni bicchiere.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/7hcgyj1571687671.jpg",
    strIngredient1: "Cherry Juice",
    strIngredient2: "Orange Peel",
    strIngredient3: "Red Chili Flakes",
    strIngredient4: "Cloves",
    strIngredient5: "Ginger",
    strIngredient6: "Vodka",
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 bottle",
    strMeasure2: "3",
    strMeasure3: "1",
    strMeasure4: "10",
    strMeasure5: "6",
    strMeasure6: "20 cl",
    strMeasure7: "",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: null,
  },
  {
    idDrink: "11566",
    strDrink: "Jewel Of The Nile",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "In a mixing glass half-filled with ice cubes, combine all of the ingredients. Stir well. Strain into a cocktail glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "In einem Mischglas, das halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut umrühren. In ein Cocktailglas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "In un mixing glass riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti. Filtrare in un bicchiere da cocktail. Mescolare bene.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/hx4nrb1504884947.jpg",
    strIngredient1: "Gin",
    strIngredient2: "Green Chartreuse",
    strIngredient3: "Yellow Chartreuse",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 1/2 oz ",
    strMeasure2: "1/2 oz ",
    strMeasure3: "1/2 oz ",
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-08 16:35:48",
  },
  {
    idDrink: "17184",
    strDrink: "Between The Sheets",
    strDrinkAlternate: null,
    strTags: "IBA,Classic",
    strVideo: "https://www.youtube.com/watch?v=5j9qfRXo2tM",
    strCategory: "Ordinary Drink",
    strIBA: "Unforgettables",
    strAlcoholic: "Alcoholic",
    strGlass: "Cocktail glass",
    strInstructions:
      "Pour all ingredients into shaker with ice cubes, shake, strain into chilled cocktail glass.",
    strInstructionsES: null,
    strInstructionsDE:
      "Alle Zutaten in den Shaker mit Eiswürfeln geben, schütteln, in ein gekühltes Cocktailglas abseihen.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Versare tutti gli ingredienti in uno shaker con cubetti di ghiaccio, shakerare e filtrare in una coppetta da cocktail ghiacciata.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/of1rj41504348346.jpg",
    strIngredient1: "Brandy",
    strIngredient2: "Light rum",
    strIngredient3: "Triple sec",
    strIngredient4: "Lemon juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz ",
    strMeasure2: "1 oz ",
    strMeasure3: "1 oz ",
    strMeasure4: "1 oz ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-09-02 11:32:26",
  },
  {
    idDrink: "178339",
    strDrink: "The Strange Weaver",
    strDrinkAlternate: null,
    strTags: "Classy",
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Mix ingredients slowly in a glass with ice, garnish with orange slice",
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT:
      "Mescolare gli ingredienti lentamente in un bicchiere con ghiaccio, guarnire con una fetta d'arancia",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/opxjzh1604179528.jpg",
    strIngredient1: "Light Rum",
    strIngredient2: "Gin",
    strIngredient3: "Sweet Vermouth",
    strIngredient4: "Campari",
    strIngredient5: "Lemon Juice",
    strIngredient6: "Orgeat Syrup",
    strIngredient7: "Orange Peel",
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 oz",
    strMeasure2: "1 oz",
    strMeasure3: "0.75 oz",
    strMeasure4: "0.75 oz",
    strMeasure5: "Dash",
    strMeasure6: "Dash",
    strMeasure7: "Garnish with",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: null,
  },
  {
    idDrink: "16134",
    strDrink: "Absolutly Screwed Up",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Shake it up it tasts better that way, but you can stir it if you want. 6 of those and you will be wasted for the rest of the night.",
    strInstructionsES:
      "Agítalo para que te sepa más delicioso, pero puedes revolverlo si quieres. 6 de esos lo mantendré borracho por el resto de la noche.",
    strInstructionsDE:
      "Schütteln Sie, schmeckt es besser, aber Sie können es auch rühren, wenn Sie wollen. 6 davon und du wirst für den Rest der Nacht erledigt sein.",
    strInstructionsFR: null,
    strInstructionsIT:
      "Agitalo perché ha un sapore migliore, ma puoi mescolarlo se vuoi.\r\n6 di quelli e sarai ubriaco per il resto della notte.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/yvxrwv1472669728.jpg",
    strIngredient1: "Absolut Citron",
    strIngredient2: "Orange juice",
    strIngredient3: "Triple sec",
    strIngredient4: "Ginger ale",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "1 shot ",
    strMeasure2: "1 shot ",
    strMeasure3: "1 shot ",
    strMeasure4: "Fill to top ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:55:28",
  },
  {
    idDrink: "16202",
    strDrink: "Amaretto Sweet & Sour",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Punch / Party Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Margarita/Coupette glass",
    strInstructions:
      'Fill the blender with 3/4 ice. Add sweet & sour mix to the top of the ice. Add about 1" of pineapple juice, 1/2" of melon liqeur, and 1/2 to 1/4" of amaretto. Then blend the mix until it is of margaritta consistency or thinner.',
    strInstructionsES:
      'Llene la licuadora 3/4 de su capacidad con hielo. Agrega la mezcla de limón encima del hielo. Agregue alrededor de 1\\" parte de jugo de piña, 1\\/2\\" de licor de melón y 1\\/2 a 1\\/4\\" de Amaretto. Luego mezcle hasta obtener una consistencia de margarita o menos espesa.',
    strInstructionsDE:
      'Füllen Sie den Mixer mit 3/4 Eis. Geben Sie die süß-saure Mischung auf die Oberseite des Eises. Füge etwa 1" Ananassaft, 1/2" Melonenlikör und 1/2 bis 1/4" Amaretto hinzu. Dann die Mischung mischen, bis sie eine Margaritta-Konsistenz oder Verdünnung aufweist.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Riempi il frullatore con 3/4 di ghiaccio.\r\nAggiungi il mix sweet & sour sulla parte superiore del ghiaccio.\r\nAggiungere circa 15ml di succo di ananas, 8ml di liquore al melone, e tra gli 8ml e 4ml di amaretto.\r\nQuindi frullare il composto fino a ottenere una consistenza margarita o più sottile.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/vswwus1472668546.jpg",
    strIngredient1: "Amaretto",
    strIngredient2: "Sweet and sour",
    strIngredient3: "Midori melon liqueur",
    strIngredient4: "Pineapple juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: null,
    strMeasure2: null,
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2016-08-31 19:35:46",
  },
  {
    idDrink: "178346",
    strDrink: "Elderflower Caipirinha",
    strDrinkAlternate: null,
    strTags: "Brazilian",
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Collins glass",
    strInstructions:
      "Take the glass and muddle the lime in it. Fill the glass with crushed ice and add the Cachaca. Stir well and top with some more crushed ice. Garnish with lime and enjoy!",
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT:
      "In un bicchiere pestare il lime. Riempi il bicchiere con ghiaccio tritato e aggiungi la cachaca. Mescola bene e aggiungi altro ghiaccio tritato. Guarnire con il lime.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/dif7a31614006331.jpg",
    strIngredient1: "Cachaca",
    strIngredient2: "Lime",
    strIngredient3: "Elderflower cordial",
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "60 ml",
    strMeasure2: "1",
    strMeasure3: "3 cl",
    strMeasure4: "",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: "https://www.instagram.com/p/CKpDNzFFKvl/",
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: null,
  },
  {
    idDrink: "178360",
    strDrink: "Lemon Elderflower Spritzer",
    strDrinkAlternate: null,
    strTags: "Summer, Fresh, Refreshing",
    strVideo: null,
    strCategory: "Cocktail",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions: "Pour all ingredients over ice, stir and enjoy!\r\n",
    strInstructionsES: null,
    strInstructionsDE: null,
    strInstructionsFR: null,
    strInstructionsIT: null,
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/125w0o1630407389.jpg",
    strIngredient1: "Elderflower cordial",
    strIngredient2: "Vodka",
    strIngredient3: "Soda Water",
    strIngredient4: "Fresh Lemon Juice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "2 tsp",
    strMeasure2: "1 shot",
    strMeasure3: "1/3 cup",
    strMeasure4: "Top",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: "https://www.instagram.com/p/CNLYC2_sdlk",
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: null,
  },
  {
    idDrink: "13200",
    strDrink: "Owen's Grandmother's Revenge",
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: "Ordinary Drink",
    strIBA: null,
    strAlcoholic: "Alcoholic",
    strGlass: "Highball glass",
    strInstructions: "Add ingredients and mix in blender.",
    strInstructionsES: null,
    strInstructionsDE: "Zutaten im Mixer vermengen.",
    strInstructionsFR: null,
    strInstructionsIT: "Aggiungere gli ingredienti e mescola nel frullatore.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    strDrinkThumb:
      "https://www.thecocktaildb.com/images/media/drink/0wt4uo1503565321.jpg",
    strIngredient1: "Whiskey",
    strIngredient2: "Beer",
    strIngredient3: "Lemonade",
    strIngredient4: "Ice",
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: "12 oz ",
    strMeasure2: "12 oz ",
    strMeasure3: "12 oz frozen ",
    strMeasure4: "1 cup crushed ",
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: "No",
    dateModified: "2017-08-24 10:02:02",
  },
];
